---
title: "BeeModeling"
author: "Nick R. Bachelder"
date: "5/10/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = "/Users/colleen/Dropbox/Fall_2014/ucsb/Bee-Specialization-Modeling/")
knitr::opts_knit$set(error=T)


library(lifecycle)
library(rvest)
library(dplyr)
library(plotly)
library(tidyverse)
library(data.table)


```

```{r, echo = False}
options(max.print=1000000)
interactions_b <- read.csv('modeling_data/interactions_dup.csv')

for (c in colnames(interactions_b)) {
  interactions_b[[c]] <-  tolower(interactions_b[[c]])
}

for (c in colnames(interactions_b)) {
  interactions_b[[c]] <-  tolower(interactions_b[[c]])
}
```

```{r}
interactions_b[1:5,]
```



Define beeCites with varying criteria

```{r, fig.width=5,fig.height=2}
beeCiteNoFilter <- interactions_b %>% 
  dplyr::select(sourceTaxonSpeciesName,targetTaxonFamilyName) %>% 
  dplyr::rename(interestBee = sourceTaxonSpeciesName, interact = targetTaxonFamilyName) %>% dplyr::group_by(interestBee, interact) %>% dplyr::count() %>% ungroup() %>% 
  filter(interestBee != "", interact != "")

TotalCitations <- beeCiteNoFilter %>% group_by(interestBee) %>% dplyr::summarise(n_Bee = sum(n)) %>% ungroup()
TotalCitations <- sum(TotalCitations$n_Bee)

beeCiteNoFilter <- beeCiteNoFilter %>% group_by(interestBee) %>% dplyr::summarise(interact= interact, n = n, n_Bee = sum(n)) %>% ungroup()
beeCiteNoFilter <- beeCiteNoFilter %>% dplyr::summarise(interestBee = interestBee, interact= interact, n = n, n_Bee = n_Bee, BeeFreq = n_Bee / TotalCitations) %>% ungroup() %>% unique()

beeIntDegree <- beeCiteNoFilter %>% dplyr::select(interestBee, interact) %>% unique() %>% group_by(interestBee, interact) %>% dplyr::count() 
beeIntDegree <- beeIntDegree %>% group_by(interestBee) %>% dplyr::summarise(interestBee = interestBee, degree = sum(n)) %>% unique()

beeIntDegreeC10 <- beeCiteNoFilter %>% dplyr::select(interestBee, interact) %>% unique() %>% group_by(interestBee, interact) %>% dplyr::count()
beeIntDegreeC10$numcitations <- beeCiteNoFilter$n
beeIntDegreeC10 <- beeIntDegreeC10 %>% filter(numcitations >= 10)
beeIntDegreeC10 <- beeIntDegreeC10 %>% group_by(interestBee) %>% dplyr::summarise(interestBee = interestBee, degree = sum(n)) %>% unique() ## min of 10 citations to contribute to degree

beeIntDegreeC5 <- beeCiteNoFilter %>% dplyr::select(interestBee, interact) %>% unique() %>% group_by(interestBee, interact) %>% dplyr::count()
beeIntDegreeC5$numcitations <- beeCiteNoFilter$n
beeIntDegreeC5 <- beeIntDegreeC5 %>% filter(numcitations >= 5)
beeIntDegreeC5 <- beeIntDegreeC5 %>% group_by(interestBee) %>% dplyr::summarise(interestBee = interestBee, degree = sum(n)) %>% unique() ## min of 5 citations to contribute to degree

beeIntDegreeW <- beeCiteNoFilter %>% dplyr::select(interestBee, interact) %>% unique() %>% group_by(interestBee, interact) %>% dplyr::count()
beeIntDegreeW$numcitations <- beeCiteNoFilter$n
beeIntDegreeW$n_Bee <- beeCiteNoFilter$n_Bee
beeIntDegreeW$n <- (beeIntDegreeW$numcitations / beeIntDegreeW$n_Bee)^2
beeIntDegreeW <- beeIntDegreeW %>% group_by(interestBee) %>% dplyr::summarise(interestBee = interestBee, degree = sum(n)) %>% unique() ## weighted degree


beeCite <-  left_join(beeCiteNoFilter, beeIntDegree, by = 'interestBee') 

beeCiteC10 <-  left_join(beeCiteNoFilter, beeIntDegreeC10, by = 'interestBee')

beeCiteC5 <-  left_join(beeCiteNoFilter, beeIntDegreeC5, by = 'interestBee')

beeCiteW <-  left_join(beeCiteNoFilter, beeIntDegreeW, by = 'interestBee')


beeCiteNoFilterGenus <- interactions_b %>% dplyr::select(sourceTaxonSpeciesName, targetTaxonGenusName) %>% 
  dplyr::rename(interestBee = sourceTaxonSpeciesName, interact = targetTaxonGenusName) %>% group_by(interestBee, interact) %>% dplyr::count() %>% ungroup() %>% 
  filter(interestBee != "", interact != "")

TotalCitationsGenus <- beeCiteNoFilterGenus %>% group_by(interestBee) %>% dplyr::summarise(n_Bee = sum(n)) %>% ungroup()
TotalCitationsGenus <- sum(TotalCitationsGenus$n_Bee)

beeCiteNoFilterGenus <- beeCiteNoFilterGenus %>% group_by(interestBee) %>% dplyr::summarise(interact= interact, n = n, n_Bee = sum(n)) %>% ungroup()
beeCiteNoFilterGenus <- beeCiteNoFilterGenus %>% dplyr::summarise(interestBee = interestBee, interact= interact, n = n, n_Bee = n_Bee, BeeFreq = n_Bee / TotalCitations) %>% ungroup()

beeIntDegreeGenus <- beeCiteNoFilterGenus %>% dplyr::select(interestBee, interact) %>% unique() %>% group_by(interestBee, interact) %>% dplyr::count()
beeIntDegreeGenus <- beeIntDegreeGenus %>% group_by(interestBee) %>% dplyr::summarise(interestBee = interestBee, degree = sum(n)) %>% unique()

beeIntDegreeC10Genus <- beeCiteNoFilterGenus %>% dplyr::select(interestBee, interact) %>% unique() %>% group_by(interestBee, interact) %>% dplyr::count()
beeIntDegreeC10Genus$numcitations <- beeCiteNoFilterGenus$n
beeIntDegreeC10Genus <- beeIntDegreeC10Genus %>% filter(numcitations >= 10)
beeIntDegreeC10Genus <- beeIntDegreeC10Genus %>% group_by(interestBee) %>% dplyr::summarise(interestBee = interestBee, degree = sum(n)) %>% unique() ## min of 10 citations to contribute to degree

beeIntDegreeC5Genus <- beeCiteNoFilterGenus %>% dplyr::select(interestBee, interact) %>% unique() %>% group_by(interestBee, interact) %>% dplyr::count()
beeIntDegreeC5Genus$numcitations <- beeCiteNoFilterGenus$n
beeIntDegreeC5Genus <- beeIntDegreeC5Genus %>% filter(numcitations >= 5)
beeIntDegreeC5Genus <- beeIntDegreeC5Genus %>% group_by(interestBee) %>% dplyr::summarise(interestBee = interestBee, degree = sum(n)) %>% unique() ## min of 5 citations to contribute to degree

beeIntDegreeWGenus <- beeCiteNoFilterGenus %>% dplyr::select(interestBee, interact) %>% unique() %>% group_by(interestBee, interact) %>% dplyr::count()
beeIntDegreeWGenus$numcitations <- beeCiteNoFilterGenus$n
beeIntDegreeWGenus$n_Bee <- beeCiteNoFilterGenus$n_Bee
beeIntDegreeWGenus$n <- (beeIntDegreeWGenus$numcitations / beeIntDegreeWGenus$n_Bee)^2
beeIntDegreeWGenus <- beeIntDegreeWGenus %>% group_by(interestBee) %>% dplyr::summarise(interestBee = interestBee, degree = sum(n)) %>% unique() ## weighted degree


beeCiteGenus <-  left_join(beeCiteNoFilterGenus, beeIntDegreeGenus, by = 'interestBee')

beeCiteC10Genus <-  left_join(beeCiteNoFilterGenus, beeIntDegreeC10Genus, by = 'interestBee')

beeCiteC5Genus <-  left_join(beeCiteNoFilterGenus, beeIntDegreeC5Genus, by = 'interestBee') 

beeCiteWGenus <-  left_join(beeCiteNoFilterGenus, beeIntDegreeWGenus, by = 'interestBee')

beeCite[1:10,]
```


```{r}
beeCiteGenus <- beeCiteGenus %>% dplyr::rename(interactGenus = interact, number_of_citations_of_genus_interaction = n, number_of_citation_for_bee_species = n_Bee, 
                        bee_proportion_of_all_bee_citations = BeeFreq, degreeGenus = degree)

beeCite <- beeCite %>% dplyr::rename(interactFamily = interact, number_of_citations_of_family_interaction = n, number_of_citation_for_bee_species = n_Bee, 
                        bee_proportion_of_all_bee_citations = BeeFreq, degreeFamily = degree)

beeCiteC5Genus <- beeCiteC5Genus %>% dplyr::rename(interactGenus = interact, number_of_citations_of_genus_interaction = n, number_of_citation_for_bee_species = n_Bee, 
                        bee_proportion_of_all_bee_citations = BeeFreq, degreeC5Genus = degree)

beeCiteC5 <- beeCiteC5 %>% dplyr::rename(interactFamily = interact, number_of_citations_of_family_interaction = n, number_of_citation_for_bee_species = n_Bee, 
                        bee_proportion_of_all_bee_citations = BeeFreq, degreeC5Family = degree)

beeCiteWGenus <- beeCiteWGenus %>% dplyr::rename(interactGenus = interact, number_of_citations_of_genus_interaction = n, number_of_citation_for_bee_species = n_Bee, 
                        bee_proportion_of_all_bee_citations = BeeFreq, degreeWGenus = degree)
beeCiteW <- beeCiteW %>% dplyr::rename(interactFamily = interact, number_of_citations_of_family_interaction = n, number_of_citation_for_bee_species = n_Bee, 
                        bee_proportion_of_all_bee_citations = BeeFreq, degreeWFamily = degree)

beeCiteW[1:5,]
```



## Include Fowler Data

```{r}
western_page <- read_html("https://jarrodfowler.com/pollen_specialist.html")
eastern_page <- read_html("https://jarrodfowler.com/specialist_bees.html")
central_page <- read_html("https://jarrodfowler.com/bees_pollen.html")


western_table <- western_page %>% html_table(fill=TRUE)
eastern_table<- eastern_page %>% html_table(fill=TRUE)
central_table<- central_page %>% html_table(fill=TRUE)


western_table <- as.data.frame(western_table) %>% dplyr::select(-Family..Subfamily..Tribe..Subtribe)
eastern_table <- as.data.frame(eastern_table) %>% dplyr::select(-Family..Subfamily..Tribe..Subtribe)
central_table <- as.data.frame(central_table) %>% dplyr::select(-Family..Subfamily..Tribe..Subtribe)

western_table$interestBee <- tolower(gsub(" *\\(.*?\\) *", "", western_table$Genus..Subgenus..species))
eastern_table$interestBee <- tolower(gsub(" *\\(.*?\\) *", "", eastern_table$Genus..Subgenus..species))
central_table$interestBee <- tolower(gsub(" *\\(.*?\\) *", "", central_table$Genus..Subgenus..species))

table <- rbind(western_table, eastern_table, central_table)
table$interestBee <- tolower(gsub(" *\\(.*?\\) *", "", table$Genus..Subgenus..species))

western_table$west_specialist <- 1
western_test <- western_table %>% dplyr::select(interestBee, west_specialist, Status) %>% dplyr::rename('Status_W' = 'Status') %>% unique()

eastern_table$east_specialist <- 1
eastern_test <- eastern_table %>% dplyr::select(interestBee, east_specialist, Status)%>% dplyr::rename('Status_E'= 'Status') %>% unique()

central_table$cent_specialist <- 1
central_test <- central_table %>% dplyr::select(interestBee, cent_specialist, Status)%>% dplyr::rename('Status_C'= 'Status') %>% unique()

tablejoining <- merge(x = western_test, y = eastern_test, by = "interestBee", all = TRUE)
table_test <- merge(x = tablejoining, y = central_test, by = "interestBee", all = TRUE)

table_test$specialist <- table_test$west_specialist + table_test$east_specialist + table_test$cent_specialist
table_test$specialist <- as.integer(table_test$specialist > 0)
table_test$specialist[is.na(table_test$specialist)] <- 0

write_csv(table_test, 'modeling_data/fowler')
```

```{r}
plotdf <- merge(beeCite, table_test, by = 'interestBee', all.x = TRUE)
plotdf$specialist <- plotdf$west_specialist + plotdf$east_specialist + plotdf$cent_specialist
plotdf$specialist <- as.integer(plotdf$specialist > 0)
plotdf$specialist[is.na(plotdf$specialist)] <- 0

write_csv(plotdf, 'modeling_data/BeeCiteRaw')
```

```{r}
plotdf <- merge(beeCiteC5, table_test, by = 'interestBee', all.x = TRUE)
plotdf$specialist <- plotdf$west_specialist + plotdf$east_specialist + plotdf$cent_specialist
plotdf$specialist <- as.integer(plotdf$specialist > 0)
plotdf$specialist[is.na(plotdf$specialist)] <- 0

write_csv(plotdf, 'modeling_data/BeeCiteC5')
```

```{r}
plotdf <- merge(beeCiteW, table_test, by = 'interestBee', all.x = TRUE)
plotdf$specialist <- plotdf$west_specialist + plotdf$east_specialist + plotdf$cent_specialist
plotdf$specialist <- as.integer(plotdf$specialist > 0)
plotdf$specialist[is.na(plotdf$specialist)] <- 0

write_csv(plotdf, 'modeling_data/BeeCiteW')
```

```{r}
plotdf <- merge(beeCiteGenus, table_test, by = 'interestBee', all.x = TRUE)
plotdf$specialist <- plotdf$west_specialist + plotdf$east_specialist + plotdf$cent_specialist
plotdf$specialist <- as.integer(plotdf$specialist > 0)
plotdf$specialist[is.na(plotdf$specialist)] <- 0

write_csv(plotdf, 'modeling_data/BeeCiteRawGenus')
```

```{r}
plotdf <- merge(beeCiteC5Genus, table_test, by = 'interestBee', all.x = TRUE)
plotdf$specialist <- plotdf$west_specialist + plotdf$east_specialist + plotdf$cent_specialist
plotdf$specialist <- as.integer(plotdf$specialist > 0)
plotdf$specialist[is.na(plotdf$specialist)] <- 0

write_csv(plotdf, 'modeling_data/BeeCiteC5Genus')
```

```{r}
plotdf <- merge(beeCiteWGenus, table_test, by = 'interestBee', all.x = TRUE)
plotdf$specialist <- plotdf$west_specialist + plotdf$east_specialist + plotdf$cent_specialist
plotdf$specialist <- as.integer(plotdf$specialist > 0)
plotdf$specialist[is.na(plotdf$specialist)] <- 0

write_csv(plotdf, 'modeling_data/BeeCiteWGenus')
```





